# Generated by Django 4.2.16 on 2026-04-12 15:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IoTDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("device_id", models.CharField(max_length=100, unique=True)),
                ("device_name", models.CharField(max_length=200)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("soil_sensor", "Soil Sensor (moisture/temp/pH)"),
                            ("weather_station", "Weather Station"),
                            ("water_meter", "Water Flow Meter"),
                            ("camera", "Field Camera"),
                            ("drone", "Drone Node"),
                            ("leaf_sensor", "Leaf Wetness Sensor"),
                            ("ndvi_sensor", "NDVI Sensor"),
                        ],
                        max_length=30,
                    ),
                ),
                ("firmware_version", models.CharField(blank=True, max_length=20)),
                (
                    "battery_level",
                    models.IntegerField(default=100, help_text="percentage"),
                ),
                (
                    "signal_strength",
                    models.IntegerField(help_text="RSSI dBm", null=True),
                ),
                ("location_lat", models.FloatField(null=True)),
                ("location_lng", models.FloatField(null=True)),
                ("is_online", models.BooleanField(default=False)),
                ("last_ping", models.DateTimeField(null=True)),
                ("installed_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iot_devices",
                        to="farms.field",
                    ),
                ),
            ],
            options={
                "db_table": "iot_devices",
            },
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("soil_moisture_pct", models.FloatField(null=True)),
                ("soil_temp_celsius", models.FloatField(null=True)),
                ("soil_ph", models.FloatField(null=True)),
                ("soil_ec", models.FloatField(help_text="dS/m", null=True)),
                ("soil_nitrogen", models.FloatField(help_text="ppm", null=True)),
                ("soil_phosphorus", models.FloatField(help_text="ppm", null=True)),
                ("soil_potassium", models.FloatField(help_text="ppm", null=True)),
                ("air_temp_celsius", models.FloatField(null=True)),
                ("humidity_pct", models.FloatField(null=True)),
                ("rainfall_mm", models.FloatField(null=True)),
                ("wind_speed_kmh", models.FloatField(null=True)),
                ("wind_direction_deg", models.FloatField(null=True)),
                ("solar_radiation", models.FloatField(help_text="W/m2", null=True)),
                ("uv_index", models.FloatField(null=True)),
                ("pressure_hpa", models.FloatField(null=True)),
                ("dew_point_celsius", models.FloatField(null=True)),
                ("leaf_wetness", models.FloatField(help_text="0-1", null=True)),
                (
                    "ndvi",
                    models.FloatField(help_text="0-1 vegetation index", null=True),
                ),
                ("canopy_temp_celsius", models.FloatField(null=True)),
                ("water_flow_lph", models.FloatField(null=True)),
                ("water_consumed_liters", models.FloatField(null=True)),
                ("is_anomaly", models.BooleanField(default=False)),
                ("anomaly_score", models.FloatField(null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="iot.iotdevice",
                    ),
                ),
            ],
            options={
                "db_table": "sensor_readings",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="sensor_read_device__8811cc_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="sensor_read_timesta_56e803_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SatelliteImagery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scan_date", models.DateField()),
                ("source", models.CharField(default="Sentinel-2", max_length=50)),
                (
                    "ndvi",
                    models.FloatField(
                        help_text="Normalized Difference Vegetation Index", null=True
                    ),
                ),
                (
                    "ndwi",
                    models.FloatField(
                        help_text="Normalized Difference Water Index", null=True
                    ),
                ),
                (
                    "evi",
                    models.FloatField(help_text="Enhanced Vegetation Index", null=True),
                ),
                (
                    "savi",
                    models.FloatField(
                        help_text="Soil Adjusted Vegetation Index", null=True
                    ),
                ),
                ("lai", models.FloatField(help_text="Leaf Area Index", null=True)),
                ("crop_health_score", models.FloatField(help_text="0-100", null=True)),
                (
                    "stress_zones_pct",
                    models.FloatField(help_text="% of field showing stress", null=True),
                ),
                ("cloud_cover_pct", models.FloatField(null=True)),
                ("rgb_image_url", models.URLField(blank=True)),
                ("ndvi_image_url", models.URLField(blank=True)),
                ("raw_data_url", models.URLField(blank=True)),
                ("ai_analysis", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="satellite_scans",
                        to="farms.field",
                    ),
                ),
            ],
            options={
                "db_table": "satellite_imagery",
                "ordering": ["-scan_date"],
                "unique_together": {("field", "scan_date")},
            },
        ),
    ]
