# Generated by Django 4.2.16 on 2026-04-12 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CropSeason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "crop_type",
                    models.CharField(
                        choices=[
                            ("wheat", "Wheat"),
                            ("rice", "Rice / Paddy"),
                            ("cotton", "Cotton"),
                            ("soybean", "Soybean"),
                            ("corn", "Corn / Maize"),
                            ("sugarcane", "Sugarcane"),
                            ("mustard", "Mustard"),
                            ("groundnut", "Groundnut"),
                            ("turmeric", "Turmeric"),
                            ("tomato", "Tomato"),
                            ("onion", "Onion"),
                            ("potato", "Potato"),
                            ("chickpea", "Chickpea"),
                            ("lentil", "Lentil / Dal"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "variety",
                    models.CharField(
                        blank=True, help_text="Seed variety/brand", max_length=100
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("kharif", "Kharif (Jun–Oct)"),
                            ("rabi", "Rabi (Nov–Apr)"),
                            ("zaid", "Zaid (Mar–Jun)"),
                            ("perennial", "Perennial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField()),
                ("sowing_date", models.DateField()),
                ("expected_harvest_date", models.DateField(blank=True, null=True)),
                ("actual_harvest_date", models.DateField(blank=True, null=True)),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("pre_sowing", "Pre-Sowing"),
                            ("sowing", "Sowing"),
                            ("germination", "Germination"),
                            ("seedling", "Seedling"),
                            ("vegetative", "Vegetative"),
                            ("flowering", "Flowering"),
                            ("grain_fill", "Grain Filling"),
                            ("maturity", "Maturity"),
                            ("harvest_ready", "Harvest Ready"),
                            ("harvested", "Harvested"),
                        ],
                        default="sowing",
                        max_length=20,
                    ),
                ),
                (
                    "seed_cost_per_acre",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "fertilizer_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "pesticide_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "irrigation_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "labour_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "other_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_yield_tons",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "selling_price_per_ton",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_seasons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_seasons",
                        to="farms.field",
                    ),
                ),
            ],
            options={
                "db_table": "crop_seasons",
                "ordering": ["-sowing_date"],
                "unique_together": {("field", "season", "year")},
            },
        ),
        migrations.CreateModel(
            name="InputApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("applied_date", models.DateField()),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("fertilizer", "Fertilizer"),
                            ("pesticide", "Pesticide"),
                            ("herbicide", "Herbicide"),
                            ("fungicide", "Fungicide"),
                            ("irrigation", "Irrigation"),
                            ("growth_reg", "Growth Regulator"),
                            ("micronutrient", "Micronutrient"),
                            ("organic", "Organic Input"),
                        ],
                        max_length=20,
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("quantity", models.FloatField()),
                ("unit", models.CharField(max_length=20)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("applied_by", models.CharField(blank=True, max_length=100)),
                ("method", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inputs",
                        to="crops.cropseason",
                    ),
                ),
            ],
            options={
                "db_table": "input_applications",
                "ordering": ["-applied_date"],
            },
        ),
        migrations.CreateModel(
            name="GrowthLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("log_date", models.DateField()),
                ("plant_height_cm", models.FloatField(null=True)),
                ("leaf_count", models.IntegerField(null=True)),
                ("canopy_cover_pct", models.FloatField(null=True)),
                (
                    "chlorophyll_spad",
                    models.FloatField(help_text="SPAD value", null=True),
                ),
                ("pest_observed", models.BooleanField(default=False)),
                ("disease_observed", models.BooleanField(default=False)),
                ("stress_signs", models.BooleanField(default=False)),
                ("observation_notes", models.TextField(blank=True)),
                (
                    "field_photo",
                    models.ImageField(blank=True, upload_to="growth_logs/"),
                ),
                ("ai_analysis", models.JSONField(default=dict)),
                ("ai_health_score", models.FloatField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growth_logs",
                        to="crops.cropseason",
                    ),
                ),
            ],
            options={
                "db_table": "growth_logs",
                "ordering": ["-log_date"],
                "unique_together": {("crop_season", "log_date")},
            },
        ),
    ]
