# Generated by Django 4.2.16 on 2026-04-12 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "total_area",
                    models.DecimalField(
                        decimal_places=2, help_text="acres", max_digits=10
                    ),
                ),
                ("location_lat", models.FloatField()),
                ("location_lng", models.FloatField()),
                ("village", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "farms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "boundary_json",
                    models.TextField(
                        blank=True, default="", help_text="GeoJSON boundary as text"
                    ),
                ),
                ("area_acres", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "soil_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clay", "Clay"),
                            ("loam", "Loam"),
                            ("sandy", "Sandy"),
                            ("silt", "Silt"),
                            ("clay_loam", "Clay Loam"),
                            ("sandy_loam", "Sandy Loam"),
                            ("black", "Black Cotton Soil"),
                            ("red", "Red Laterite"),
                            ("alluvial", "Alluvial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("soil_ph", models.FloatField(blank=True, null=True)),
                ("organic_matter", models.FloatField(blank=True, null=True)),
                (
                    "irrigation_type",
                    models.CharField(
                        choices=[
                            ("drip", "Drip"),
                            ("sprinkler", "Sprinkler"),
                            ("flood", "Flood"),
                            ("rainfed", "Rain-fed"),
                            ("canal", "Canal"),
                            ("none", "None"),
                        ],
                        default="drip",
                        max_length=20,
                    ),
                ),
                ("water_source", models.CharField(blank=True, max_length=100)),
                ("irrigation_capacity_lph", models.FloatField(blank=True, null=True)),
                ("is_fallow", models.BooleanField(default=False)),
                ("last_crop", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "db_table": "fields",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SoilReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tested_by", models.CharField(blank=True, max_length=100)),
                ("test_date", models.DateField()),
                ("nitrogen", models.FloatField(null=True)),
                ("phosphorus", models.FloatField(null=True)),
                ("potassium", models.FloatField(null=True)),
                ("zinc", models.FloatField(null=True)),
                ("iron", models.FloatField(null=True)),
                ("manganese", models.FloatField(null=True)),
                ("boron", models.FloatField(null=True)),
                ("copper", models.FloatField(null=True)),
                ("ph", models.FloatField(null=True)),
                ("ec", models.FloatField(null=True)),
                ("organic_carbon", models.FloatField(null=True)),
                ("ai_health_score", models.FloatField(null=True)),
                ("ai_recommendations", models.JSONField(default=list)),
                (
                    "report_file",
                    models.FileField(blank=True, upload_to="soil_reports/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_reports",
                        to="farms.field",
                    ),
                ),
            ],
            options={
                "db_table": "soil_reports",
                "ordering": ["-test_date"],
            },
        ),
    ]
