# Generated by Django 4.2.16 on 2026-04-12 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("disease", "Disease Detection"),
                            ("pest", "Pest Risk"),
                            ("irrigation", "Irrigation Required"),
                            ("yield", "Yield Warning"),
                            ("weather", "Weather Alert"),
                            ("soil", "Soil Issue"),
                            ("satellite", "Satellite Anomaly"),
                            ("price", "Market Price Alert"),
                            ("sensor", "Sensor Anomaly"),
                            ("harvest", "Harvest Window"),
                            ("general", "General Advisory"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical — Immediate Action"),
                            ("high", "High — Action within 24hrs"),
                            ("medium", "Medium — Monitor"),
                            ("low", "Low — Informational"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("message", models.TextField()),
                ("action_required", models.TextField(blank=True)),
                ("ml_model", models.CharField(blank=True, max_length=50)),
                ("ml_confidence", models.FloatField(null=True)),
                ("ml_payload", models.JSONField(default=dict)),
                (
                    "estimated_loss_inr",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "estimated_saving_inr",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("push_sent", models.BooleanField(default=False)),
                ("sms_sent", models.BooleanField(default=False)),
                ("email_sent", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="farms.farm",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="farms.field",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "created_at"],
                        name="alerts_user_id_174a2c_idx",
                    ),
                    models.Index(
                        fields=["farm", "severity", "is_resolved"],
                        name="alerts_farm_id_9cb9ea_idx",
                    ),
                ],
            },
        ),
    ]
