services:
  - type: web
    name: harvestia-app
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://harvestia-api.onrender.com/api/v1
      - key: VITE_WS_URL
        value: wss://harvestia-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
